name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main       # Trigger deployment on main branch
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    name: Build and Deploy Job

    steps:
      # 1. Checkout repo
      - uses: actions/checkout@v3

      # 2. Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'  # Adjust to your project's Node version

      # 3. Install dependencies
      - name: Install dependencies
        run: npm ci

      # 4. Build the project
      - name: Build
        run: npm run build

      # 5. Deploy to Azure Static Web Apps
      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          action: "upload"
          #### Adjust app_location / output_location to your project structure ####
          app_location: "/"             # Root of your repo
          output_location: "build"      # React default build folder
